<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ciudad extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ciudad_model');
    }


    /*
     * Listing of ciudades
     */
    function index()
    {
        $this->load->library('pagination');
        $params['limit'] = 5;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('ciudad/index?');
        $config['total_rows'] = $this->Ciudad_model->get_all_ciudades_count();
        $config['per_page'] = 20;
        $this->pagination->initialize($config);

        $data['ciudades'] = $this->Ciudad_model->obtener_ciudades($params);

        $data['_view'] = 'ciudad/index';
        print_r($data);
    }


    
}
