<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Colectivo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Colectivo_model');
    } 

    /*
     * Listing of colectivos
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('colectivo/index?');
        $config['total_rows'] = $this->Colectivo_model->get_all_colectivos_count();
        $this->pagination->initialize($config);

        $data['colectivos'] = $this->Colectivo_model->get_all_colectivos($params);
        
        $data['_view'] = 'colectivo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new colectivo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('capacidadInferior','CapacidadInferior','required|integer');
		$this->form_validation->set_rules('capacidadSuperior','CapacidadSuperior','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'capacidadInferior' => $this->input->post('capacidadInferior'),
				'capacidadSuperior' => $this->input->post('capacidadSuperior'),
            );
            
            $colectivo_id = $this->Colectivo_model->add_colectivo($params);
            redirect('colectivo/index');
        }
        else
        {            
            $data['_view'] = 'colectivo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a colectivo
     */
    function edit($idColectivo)
    {   
        // check if the colectivo exists before trying to edit it
        $data['colectivo'] = $this->Colectivo_model->get_colectivo($idColectivo);
        
        if(isset($data['colectivo']['idColectivo']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('capacidadInferior','CapacidadInferior','required|integer');
			$this->form_validation->set_rules('capacidadSuperior','CapacidadSuperior','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'capacidadInferior' => $this->input->post('capacidadInferior'),
					'capacidadSuperior' => $this->input->post('capacidadSuperior'),
                );

                $this->Colectivo_model->update_colectivo($idColectivo,$params);            
                redirect('colectivo/index');
            }
            else
            {
                $data['_view'] = 'colectivo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The colectivo you are trying to edit does not exist.');
    } 

    /*
     * Deleting colectivo
     */
    function remove($idColectivo)
    {
        $colectivo = $this->Colectivo_model->get_colectivo($idColectivo);

        // check if the colectivo exists before trying to delete it
        if(isset($colectivo['idColectivo']))
        {
            $this->Colectivo_model->delete_colectivo($idColectivo);
            redirect('colectivo/index');
        }
        else
            show_error('The colectivo you are trying to delete does not exist.');
    }
    
}
