<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Frecuencia extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Frecuencia_model');
    } 

    /*
     * Listing of frecuencias
     */
    function index()
    {
        $this->load->library('pagination');
        $params['limit'] = 10;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('frecuencia/index?');
        $config['total_rows'] = $this->Frecuencia_model->get_all_frecuencias_count();
        $this->pagination->initialize($config);

        $data['frecuencias'] = $this->Frecuencia_model->get_all_frecuencias($params);
        
        $data['_view'] = 'frecuencia/index';
        print_r($data);
    }


}
