<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Viaje extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Viaje_model');
    } 


    function agregarViajes(){
        $this->load->model('Ciudad_model');
        $data['ciudades'] = $this->Ciudad_model->obtener_ciudades();

        $this->load->model('Colectivo_model');
        $data['colectivos'] = $this->Colectivo_model->ObtenerColectivo();

        $this->load->view('viaje/add.php', $data);
    }

    function agregarFrecuenciasViajes(){
        $this->load->library('form_validation');

        print_r($this->input->post());

        $this->form_validation->set_rules('ciudadOrigen', 'ciudad Origen', 'trim|required');
        $this->form_validation->set_rules('CiudadDestino', 'ciudad Destino', 'trim|required|differs[ciudadOrigen]');
        $this->form_validation->set_rules('tarifa', 'tarifa', 'trim|required');
        $this->form_validation->set_rules('ColectivoID', 'Colectivo ID', 'trim|required');
        $data['ciudadOrigen'] = $this->input->post('ciudadOrigen');
        $data['CiudadDestino'] = $this->input->post('CiudadDestino');
        $data['tarifa'] = $this->input->post('tarifa');
        $data['ColectivoID'] = $this->input->post('ColectivoID');
        if ($this->form_validation->run() == TRUE) {
            $this->load->view('viaje/agregarFrecuencia', $data);
        } else {
            $this->agregarViajes();
        }
    }

    function AgregadoViaje(){
        print_r($this->input->post());
    }

    function obtenerViajesporID(){
        $origen = $this->input->post('Origen');
        $viajes = $this->Viaje_model->get_viaje($origen);
        echo json_encode($viajes);
    }

    

    function BuscarPasajes(){
        $origen = $this->input->post('Origen');
        $destino = $this->input->post('Destino');
        $dia = $this->input->post('Dia');
        $viajes = $this->Viaje_model->buscarPasajes($origen,$destino, $dia);

        echo json_encode($viajes);
    }

    
    function obtenerFechasViajes(){
        $origen = $this->input->post('Origen');
        $destino = $this->input->post('Destino');
        $viajes = $this->Viaje_model->obtenerFechaViajes($origen,$destino);
        echo json_encode($viajes);
    }

    /*
     * Listing of viajes
     */
    function index()
    {
        $this->load->library('pagination');
        $params['limit'] = 5;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('viaje/index?');
        $config['total_rows'] = $this->Viaje_model->get_all_viajes_count();
        $this->pagination->initialize($config);

        $data['viajes'] = $this->Viaje_model->get_all_viajes($params);
        
        $data['_view'] = 'viaje/index';
        print_r($data);
    }

    /*
     * Adding a new viaje
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('idcolectivo','Idcolectivo','required|integer');
		$this->form_validation->set_rules('idciudadorigen','Idciudadorigen','required|integer');
		$this->form_validation->set_rules('idciudadestino','Idciudadestino','required|integer');
		$this->form_validation->set_rules('tarifa','Tarifa','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'idcolectivo' => $this->input->post('idcolectivo'),
				'idciudadorigen' => $this->input->post('idciudadorigen'),
				'idciudadestino' => $this->input->post('idciudadestino'),
				'tarifa' => $this->input->post('tarifa'),
            );
            
            $viaje_id = $this->Viaje_model->add_viaje($params);
            redirect('viaje/index');
        }
        else
        {
			$this->load->model('Colectivo_model');
			$data['all_colectivos'] = $this->Colectivo_model->get_all_colectivos();

			$this->load->model('Ciudad_model');
			$data['all_ciudades'] = $this->Ciudad_model->get_all_ciudades();
			$data['all_ciudades'] = $this->Ciudad_model->get_all_ciudades();
            
            $data['_view'] = 'viaje/add';
            $this->load->view('layouts/main',$data);
        }
    }  

}
