<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Viaje extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Viaje_model');
    } 
    

    function obtenerViajesporID(){
        $origen = $this->input->post('Origen');
        $viajes = $this->Viaje_model->get_viaje($origen);
        echo json_encode($viajes);
    }

    function BuscarPasajes(){
        $origen = $this->input->post('Origen');
        $destino = $this->input->post('Destino');
        $idViaje = $this->input->post('idViaje');

        $viajes = $this->Viaje_model->buscarPasajes($origen,$destino,$idViaje);

        print_r($viajes);
    }
    

    /*
     * Listing of viajes
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('viaje/index?');
        $config['total_rows'] = $this->Viaje_model->get_all_viajes_count();
        $this->pagination->initialize($config);

        $data['viajes'] = $this->Viaje_model->get_all_viajes($params);
        
        $data['_view'] = 'viaje/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new viaje
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('idcolectivo','Idcolectivo','required|integer');
		$this->form_validation->set_rules('idciudadorigen','Idciudadorigen','required|integer');
		$this->form_validation->set_rules('idciudadestino','Idciudadestino','required|integer');
		$this->form_validation->set_rules('tarifa','Tarifa','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'idcolectivo' => $this->input->post('idcolectivo'),
				'idciudadorigen' => $this->input->post('idciudadorigen'),
				'idciudadestino' => $this->input->post('idciudadestino'),
				'tarifa' => $this->input->post('tarifa'),
            );
            
            $viaje_id = $this->Viaje_model->add_viaje($params);
            redirect('viaje/index');
        }
        else
        {
			$this->load->model('Colectivo_model');
			$data['all_colectivos'] = $this->Colectivo_model->get_all_colectivos();

			$this->load->model('Ciudad_model');
			$data['all_ciudades'] = $this->Ciudad_model->get_all_ciudades();
			$data['all_ciudades'] = $this->Ciudad_model->get_all_ciudades();
            
            $data['_view'] = 'viaje/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a viaje
     */
    function edit($idViaje)
    {   
        // check if the viaje exists before trying to edit it
        $data['viaje'] = $this->Viaje_model->get_viaje($idViaje);
        
        if(isset($data['viaje']['idViaje']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('idcolectivo','Idcolectivo','required|integer');
			$this->form_validation->set_rules('idciudadorigen','Idciudadorigen','required|integer');
			$this->form_validation->set_rules('idciudadestino','Idciudadestino','required|integer');
			$this->form_validation->set_rules('tarifa','Tarifa','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'idcolectivo' => $this->input->post('idcolectivo'),
					'idciudadorigen' => $this->input->post('idciudadorigen'),
					'idciudadestino' => $this->input->post('idciudadestino'),
					'tarifa' => $this->input->post('tarifa'),
                );

                $this->Viaje_model->update_viaje($idViaje,$params);            
                redirect('viaje/index');
            }
            else
            {
				$this->load->model('Colectivo_model');
				$data['all_colectivos'] = $this->Colectivo_model->get_all_colectivos();

				$this->load->model('Ciudad_model');
				$data['all_ciudades'] = $this->Ciudad_model->get_all_ciudades();
				$data['all_ciudades'] = $this->Ciudad_model->get_all_ciudades();

                $data['_view'] = 'viaje/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The viaje you are trying to edit does not exist.');
    } 

    /*
     * Deleting viaje
     */
    function remove($idViaje)
    {
        $viaje = $this->Viaje_model->get_viaje($idViaje);

        // check if the viaje exists before trying to delete it
        if(isset($viaje['idViaje']))
        {
            $this->Viaje_model->delete_viaje($idViaje);
            redirect('viaje/index');
        }
        else
            show_error('The viaje you are trying to delete does not exist.');
    }
    
}
