<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ciudad_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ciudad by idCiudad
     */
    function get_ciudad($idCiudad)
    {
        return $this->db->get_where('ciudad',array('idCiudad'=>$idCiudad))->row_array();
    }
    
    /*
     * Get all ciudades count
     */
    function get_all_ciudades_count()
    {
        $this->db->from('ciudad');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all ciudades
     */
    function obtener_ciudades()
    {
        $this->db->order_by('nombreCiudad', 'desc');

        return $this->db->get('ciudad')->result_object();
    }
        
    /*
     * function to add new ciudad
     */
    function add_ciudad($params)
    {
        $this->db->insert('ciudad',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ciudad
     */
    function update_ciudad($idCiudad,$params)
    {
        $this->db->where('idCiudad',$idCiudad);
        return $this->db->update('ciudad',$params);
    }
    
    /*
     * function to delete ciudad
     */
    function delete_ciudad($idCiudad)
    {
        return $this->db->delete('ciudad',array('idCiudad'=>$idCiudad));
    }
}
