<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Viaje_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get viaje by idViaje
     */
    function get_viaje($idViaje)
    {
        $this->db->where('idciudadorigen', $idViaje);
        $this->db->join('ciudad', 'ciudad.idCiudad = viaje.idciudadestino');
        return $this->db->get('viaje')->result_object();
    }

    function buscarPasajes($idOrigen, $idDestino, $idViaje)
    {
        $this->db->select('*');
        $this->db->from('viaje');
        $this->db->join('ciudad', 'ciudad.idCiudad = viaje.idciudadestino', 'inner');
        $this->db->join('frecuencia', 'frecuencia.idFrecuencia = viaje.idciudadestino', 'inner');
        $this->db->join('ciudad', 'ciudad.idCiudad = viaje.idciudadestino');    
        $this->db->join('ciudad', 'ciudad.idCiudad = viaje.idciudadorigen');
        $this->db->where('idciudadorigen', $idOrigen);
        $this->db->where('idciudaddestino', $idDestino);
        return $this->db->get();
    }
    
    
    /*
     * Get all viajes count
     */
    function get_all_viajes_count()
    {
        $this->db->from('viaje');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all viajes
     */
    function get_all_viajes($params = array())
    {
        $this->db->order_by('idViaje', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('viaje')->result_array();
    }
        
    /*
     * function to add new viaje
     */
    function add_viaje($params)
    {
        $this->db->insert('viaje',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update viaje
     */
    function update_viaje($idViaje,$params)
    {
        $this->db->where('idViaje',$idViaje);
        return $this->db->update('viaje',$params);
    }
    
    /*
     * function to delete viaje
     */
    function delete_viaje($idViaje)
    {
        return $this->db->delete('viaje',array('idViaje'=>$idViaje));
    }
}
